name: "Deploy backend to Google Cloud Run"

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    concurrency: frontend

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
        
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: "Authenticating to Google Cloud using Workload Identity Pool"
        id: google-auth
        uses: 'google-github-actions/auth@v2'
        if: ${{ !env.ACT }}
        with:
          project_id: '${{ vars.GCP_PROJECT_NAME }}'
          workload_identity_provider: '${{ vars.GCP_WI_PROVIDER }}'
          service_account: ${{ vars.GCP_WI_SERVICE_ACCOUNT }}
          create_credentials_file: true

      - name: "Authenticating to Google Cloud using local creds"
        uses: 'google-github-actions/auth@v2'
        if: ${{ env.ACT }}
        with:
          project_id: '${{ vars.GCP_PROJECT_NAME }}'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_NAME }}

      - name: "Configure & auth Docker for GCP"
        run: |-
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet

      - name: "Setup Docker Buildx instance"
        uses: docker/setup-buildx-action@v3

      - name: "Build and push Docker image"
        uses: docker/build-push-action@v5
        with:
          file: ./backend/Dockerfile
          context: .
          push: true
          tags: ${{ vars.GAR_LOCATION }}/langchain-extract:latest
          build-args: |
            HTTP_PORT=3000
          secret-files: |
            gacreds=${{ steps.google-auth.outputs.credentials_file_path }}
          cache-from: type=gha,scope=${{ github.ref_name }}-image
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-image

      - name: "Deploy to Cloud Run"
        uses: google-github-actions/deploy-cloudrun@v1
        id: gcr-deploy
        with:
          image: ${{ vars.GAR_LOCATION }}/langchain-extract:latest
          service: langchain-extract-gha
          region: ${{ vars.GCP_REGION }}
          flags: |
            --ingress=internal-and-cloud-load-balancing
            --port=3000
            --service-account=${{ vars.GCR_SERVICE_ACCOUNT_EMAIL }}
            --allow-unauthenticated

      - name: "Publish deployed Cloud Run URL"
        run: echo "Deployed to ${{ steps.gcr-deploy.outputs.url }}"